-- Datos iniciales para pruebas
INSERT INTO frequency_table (term, frequency, last_used, created_at) VALUES
('javascript', 5000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('java', 4500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('python', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('react', 3500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('angular', 3000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('vue', 2500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('typescript', 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('spring boot', 1800, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('spring', 1500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('docker', 1200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
